/**
 * =============================================================================
 * RUTAS STYLES — Estilos de la pantalla de rutas
 * =============================================================================
 *
 * PROPÓSITO:
 * Define todos los estilos usados en RutasView: mapa, cards de rutas,
 * vista de detalle, pasos y navegación CarPlay.
 */
import { Colors, Typography, Spacing, AppTracking } from '@/shared/constants';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.appBackground },
  scrollContent: { paddingBottom: 80 },
  mapContainer: {
    height: 280,
    position: 'relative',
  },
  mapGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 60,
  },
  utpMarker: {
    alignItems: 'center',
    gap: 2,
  },
  utpLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.onPrimary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: Colors.appPrimary,
    borderRadius: 9999,
    overflow: 'hidden',
  },
  utpCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  userMarkerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
  },
  userPulse: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
  },
  userCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  originDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  destDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  rutasList: {
    paddingHorizontal: 20,
    gap: 12,
  },
  rutasHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 4,
  },
  rutasTitle: {
    fontSize: Typography.headlineSm.fontSize,
    fontFamily: Typography.fontHankenGrotesk,
    fontWeight: Typography.headlineSm.fontWeight,
  },
  rutasSubtitle: {
    fontSize: Typography.bodySm.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodySm.fontWeight,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  liveText: {
    fontSize: Typography.labelCapsSm.fontSize,
    fontFamily: Typography.fontJetBrainsMono,
    fontWeight: Typography.labelCapsSm.fontWeight,
    letterSpacing: AppTracking.wideLabel,
  },
  rutaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  rutaAccent: {
    width: 4,
    height: 56,
    borderRadius: 2,
  },
  rutaIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rutaIconText: {
    fontSize: 16,
    fontWeight: '800',
    fontFamily: Typography.fontHankenGrotesk,
  },
  rutaInfo: {
    flex: 1,
    gap: 3,
  },
  rutaEmpresa: {
    fontSize: Typography.bodyMdMedium.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodyMdMedium.fontWeight,
  },
  rutaRecorrido: {
    fontSize: Typography.bodySm.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodySm.fontWeight,
  },
  rutaRight: {
    alignItems: 'flex-end',
    gap: 2,
    marginRight: 8,
  },
  rutaLlega: {
    fontSize: Typography.bodyMdMedium.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodyMdMedium.fontWeight,
  },
  rutaLlegaLabel: {
    fontSize: Typography.labelCapsSm.fontSize,
    fontFamily: Typography.fontJetBrainsMono,
    fontWeight: Typography.labelCapsSm.fontWeight,
    letterSpacing: AppTracking.wideLabel,
  },
  detailContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 20,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 12,
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  infoAccent: {
    width: 6,
    height: 48,
    borderRadius: 3,
  },
  infoEmpresa: {
    fontSize: Typography.headlineSm.fontSize,
    fontFamily: Typography.fontHankenGrotesk,
    fontWeight: Typography.headlineSm.fontWeight,
  },
  infoDestino: {
    fontSize: Typography.bodySm.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodySm.fontWeight,
  },
  llegaBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  llegaLabel: {
    fontSize: Typography.labelCapsMd.fontSize,
    fontFamily: Typography.fontJetBrainsMono,
    fontWeight: Typography.labelCapsMd.fontWeight,
    letterSpacing: AppTracking.wideLabel,
  },
  llegaValue: {
    fontSize: Typography.displayNumberMd.fontSize,
    fontFamily: Typography.fontHankenGrotesk,
    fontWeight: Typography.displayNumberMd.fontWeight,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  pasosSection: {
    gap: 12,
  },
  pasosTitle: {
    fontSize: Typography.headlineXs.fontSize,
    fontFamily: Typography.fontHankenGrotesk,
    fontWeight: Typography.headlineXs.fontWeight,
  },
  pasoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  pasoIconCol: {
    alignItems: 'center',
    width: 24,
  },
  pasoCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pasoLine: {
    width: 2,
    height: 36,
  },
  pasoTitle: {
    fontSize: Typography.bodyMd.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodyMd.fontWeight,
  },
  pasoSubtitle: {
    fontSize: Typography.bodySm.fontSize,
    fontFamily: Typography.fontBeVietnam,
    fontWeight: Typography.bodySm.fontWeight,
  },
  ctaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: Colors.primaryContainer,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  ctaText: {
    fontSize: Typography.headlineSm.fontSize,
    fontFamily: Typography.fontHankenGrotesk,
    fontWeight: Typography.headlineSm.fontWeight,
  },
  rutaSeguraBadge: {
    position: 'absolute',
    top: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 9999,
    backgroundColor: Colors.tertiary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  rutaSeguraText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  carContainer: { flex: 1, backgroundColor: '#0a0a0a' },
  carTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 12,
  },
  carNavLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.onPrimary + 'B3',
    letterSpacing: 1.5,
  },
  carRutaNombre: {
    fontSize: 18,
    fontWeight: '900',
    color: Colors.onPrimary,
    fontFamily: Typography.fontHankenGrotesk,
  },
  carFinishButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 9999,
    backgroundColor: Colors.onPrimary + '26',
  },
  carFinishText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.onPrimary,
    letterSpacing: 0.5,
  },
  carMapContainer: {
    height: '60%',
  },
  carBottomPanel: {
    flex: 1,
    padding: 20,
    gap: 14,
  },
  carInstructionIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carInstructionText: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.onPrimary,
    fontFamily: Typography.fontHankenGrotesk,
  },
  carInstructionDist: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.onPrimary + '99',
    marginTop: 4,
  },
  carProgressTrack: {
    height: 4,
    backgroundColor: Colors.onPrimary + '33',
    borderRadius: 2,
    overflow: 'hidden',
  },
  carProgressFill: {
    height: '100%',
    borderRadius: 2,
  },
  carMetaLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.onPrimary + '80',
    letterSpacing: 1.5,
  },
  carMetaValue: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.onPrimary,
    fontFamily: Typography.fontHankenGrotesk,
  },
  carMarkerDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.onPrimary,
  },
});

export default styles;
